const PUZZLE={"title":"Daily Grid","width":11,"height":11,"grid":["P###COOKIE#","O######A###","R#ALCATRAZ#","C####I#L##H","HOME#R####A","##A##PHILLY","##N##O####L","##D##R####E","##YOUTUBE#Y","#######I###","##COMMIT###"],"entries":[{"number":1,"direction":"down","answer":"PORCH","row":0,"col":0,"clue":"Where coffee became part of our new Philly routine"},{"number":2,"direction":"across","answer":"COOKIE","row":0,"col":4,"clue":"The correct kind is chocolate chip"},{"number":3,"direction":"down","answer":"KARL","row":0,"col":7,"clue":"The bad one, obviously"},{"number":4,"direction":"across","answer":"ALCATRAZ","row":2,"col":2,"clue":"Where she voluntarily got trapped with me on our first date"},{"number":5,"direction":"down","answer":"AIRPORT","row":2,"col":5,"clue":"Where we first met in person"},{"number":6,"direction":"down","answer":"HAYLEY","row":3,"col":10,"clue":"The coolest girl in the world, according to Mandy (and no, it’s not her)"},{"number":7,"direction":"across","answer":"HOME","row":4,"col":0,"clue":"What we’re building with Poppy, Karl, and a lot of porch coffee"},{"number":8,"direction":"down","answer":"MANDY","row":4,"col":2,"clue":"My favorite person to fall asleep to Bob’s Burgers with"},{"number":9,"direction":"across","answer":"PHILLY","row":5,"col":5,"clue":"Where our next chapter started"},{"number":10,"direction":"across","answer":"YOUTUBE","row":8,"col":2,"clue":"Home of builders, murder docs, and an unreasonable number of our evenings"},{"number":11,"direction":"down","answer":"BIT","row":8,"col":7,"clue":"What a certain Hinge profile said to commit to"},{"number":12,"direction":"across","answer":"COMMIT","row":10,"col":2,"clue":"What that Hinge profile told me to do — apparently I listened"}],"reveal":"WILL YOU MARRY ME?"};
const gridEl=document.querySelector("#grid"),activeClueEl=document.querySelector("#activeClue"),input=document.querySelector("#mobileInput");
const values=Array.from({length:11},()=>Array(11).fill("")),cells=[],entryCells=[],cellEntries=new Map();
let activeEntry=0,activePos=0,solved=false,start=Date.now();
const key=(r,c)=>r+","+c;
PUZZLE.entries.forEach((e,i)=>{const dr=e.direction==="down"?1:0,dc=e.direction==="across"?1:0;entryCells[i]=[];for(let p=0;p<e.answer.length;p++){const k=key(e.row+dr*p,e.col+dc*p);entryCells[i].push(k);if(!cellEntries.has(k))cellEntries.set(k,[]);cellEntries.get(k).push(i)}});
const startNumbers=new Map(PUZZLE.entries.map(e=>[key(e.row,e.col),e.number]));
for(let r=0;r<11;r++){cells[r]=[];for(let c=0;c<11;c++){const ch=PUZZLE.grid[r][c],b=document.createElement("button");b.type="button";b.className=ch==="#"?"cell block":"cell";b.dataset.r=r;b.dataset.c=c;if(ch!=="#"){const n=startNumbers.get(key(r,c));if(n){const s=document.createElement("span");s.className="num";s.textContent=n;b.appendChild(s)}const l=document.createElement("span");l.className="letter";b.appendChild(l);b.addEventListener("click",()=>selectCell(r,c,true))}gridEl.appendChild(b);cells[r][c]=b}}
function renderClues(){for(const dir of ["across","down"]){const list=document.querySelector("#"+dir);PUZZLE.entries.forEach((e,i)=>{if(e.direction!==dir)return;const li=document.createElement("li");li.dataset.entry=i;li.innerHTML='<span class="n">'+e.number+'</span><span class="t">'+e.clue+'</span>';li.onclick=()=>setEntry(i,0,true);list.appendChild(li)})}}
function setEntry(i,pos=0,focus=false){activeEntry=i;activePos=Math.max(0,Math.min(pos,entryCells[i].length-1));paint();if(focus)input.focus({preventScroll:true})}
function selectCell(r,c,toggle){const es=cellEntries.get(key(r,c))||[];if(!es.length)return;let i=es[0];if(toggle&&es.length>1&&es.includes(activeEntry))i=es[(es.indexOf(activeEntry)+1)%es.length];else if(es.includes(activeEntry))i=activeEntry;const p=entryCells[i].indexOf(key(r,c));setEntry(i,p,true)}
function paint(){document.querySelectorAll(".cell").forEach(x=>x.classList.remove("active","word"));document.querySelectorAll(".clues li").forEach(x=>x.classList.remove("active"));entryCells[activeEntry].forEach(k=>{const [r,c]=k.split(",").map(Number);cells[r][c].classList.add("word")});const k=entryCells[activeEntry][activePos],[r,c]=k.split(",").map(Number);cells[r][c].classList.add("active");const e=PUZZLE.entries[activeEntry];activeClueEl.innerHTML="<b>"+e.number+(e.direction==="across"?"A":"D")+"</b>"+e.clue;document.querySelector('.clues li[data-entry="'+activeEntry+'"]')?.classList.add("active")}
function putLetter(ch){if(solved)return;const k=entryCells[activeEntry][activePos],[r,c]=k.split(",").map(Number);values[r][c]=ch;cells[r][c].querySelector(".letter").textContent=ch;cells[r][c].classList.remove("wrong");if(activePos<entryCells[activeEntry].length-1)activePos++;else nextEntry();paint();testSolved()}
function erase(){if(solved)return;let k=entryCells[activeEntry][activePos],[r,c]=k.split(",").map(Number);if(!values[r][c]&&activePos>0){activePos--;k=entryCells[activeEntry][activePos];[r,c]=k.split(",").map(Number)}values[r][c]="";cells[r][c].querySelector(".letter").textContent="";paint()}
function nextEntry(delta=1){activeEntry=(activeEntry+delta+PUZZLE.entries.length)%PUZZLE.entries.length;activePos=0;paint()}
function allFilled(){for(let r=0;r<11;r++)for(let c=0;c<11;c++)if(PUZZLE.grid[r][c]!=="#"&&!values[r][c])return false;return true}
function isCorrect(){for(let r=0;r<11;r++)for(let c=0;c<11;c++)if(PUZZLE.grid[r][c]!=="#"&&values[r][c]!==PUZZLE.grid[r][c])return false;return true}
function testSolved(){if(allFilled()&&isCorrect())finish()}
function finish(){if(solved)return;solved=true;localStorage.removeItem("daily-grid-progress");setTimeout(()=>{const overlay=document.querySelector("#reveal");overlay.hidden=false;const out=document.querySelector("#revealText");let delay=0;for(const ch of PUZZLE.reveal){const s=document.createElement("span");if(ch===" "){s.className="space";s.innerHTML="&nbsp;"}else{s.textContent=ch}s.style.animationDelay=delay+"ms";out.appendChild(s);delay+=ch===" "?80:145}},650)}
function save(){if(solved)return;localStorage.setItem("daily-grid-progress",JSON.stringify(values))}
function load(){try{const v=JSON.parse(localStorage.getItem("daily-grid-progress"));if(!v)return;for(let r=0;r<11;r++)for(let c=0;c<11;c++)if(v[r]?.[c]){values[r][c]=v[r][c];cells[r][c].querySelector(".letter").textContent=v[r][c]}}catch{}}
function check(){let wrong=0;for(let r=0;r<11;r++)for(let c=0;c<11;c++){if(PUZZLE.grid[r][c]!=="#"&&values[r][c]&&values[r][c]!==PUZZLE.grid[r][c]){cells[r][c].classList.add("wrong");wrong++}}toast(wrong?wrong+" letter"+(wrong===1?"":"s")+" to revisit":"Looking good so far")}
function toast(t){const x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1500)}
document.addEventListener("keydown",e=>{if(solved)return;if(/^[a-zA-Z]$/.test(e.key)){e.preventDefault();putLetter(e.key.toUpperCase())}else if(e.key==="Backspace"){e.preventDefault();erase()}else if(e.key==="Tab"||e.key==="Enter"){e.preventDefault();nextEntry(e.shiftKey?-1:1)}else if(e.key==="ArrowRight"||e.key==="ArrowDown"){e.preventDefault();if(activePos<entryCells[activeEntry].length-1)activePos++;else nextEntry();paint()}else if(e.key==="ArrowLeft"||e.key==="ArrowUp"){e.preventDefault();if(activePos>0)activePos--;else nextEntry(-1);paint()}});
input.addEventListener("input",()=>{const s=input.value.toUpperCase().replace(/[^A-Z]/g,"");if(s)putLetter(s.at(-1));input.value=""});input.addEventListener("keydown",e=>{if(e.key==="Backspace"){e.preventDefault();erase()}});
document.querySelector("#prev").onclick=()=>nextEntry(-1);document.querySelector("#next").onclick=()=>nextEntry(1);document.querySelector("#check").onclick=check;
setInterval(()=>{if(!solved){const s=Math.floor((Date.now()-start)/1000);document.querySelector("#timer").textContent=Math.floor(s/60)+":"+String(s%60).padStart(2,"0");save()}},1000);
renderClues();load();setEntry(0,0);